# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto_files/feed.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'app/proto_files/feed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pp/proto_files/feed.proto\x12\x04\x66\x65\x65\x64\"`\n\x08\x46\x65\x65\x64Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\"2\n\x0c\x46\x65\x65\x64ItemList\x12\"\n\nfeed_items\x18\x01 \x03(\x0b\x32\x0e.feed.FeedItem\"@\n\x0eGetFeedRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"S\n\x0c\x46\x65\x65\x64Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12!\n\tfeed_item\x18\x03 \x01(\x0b\x32\x0e.feed.FeedItem\"[\n\x0fGetFeedResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\nfeed_items\x18\x03 \x01(\x0b\x32\x12.feed.FeedItemList2\xb2\x01\n\x0b\x46\x65\x65\x64Service\x12\x38\n\x07GetFeed\x12\x14.feed.GetFeedRequest\x1a\x15.feed.GetFeedResponse\"\x00\x12\x31\n\tAddToFeed\x12\x0e.feed.FeedItem\x1a\x12.feed.FeedResponse\"\x00\x12\x36\n\x0eRemoveFromFeed\x12\x0e.feed.FeedItem\x1a\x12.feed.FeedResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto_files.feed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDITEM']._serialized_start=36
  _globals['_FEEDITEM']._serialized_end=132
  _globals['_FEEDITEMLIST']._serialized_start=134
  _globals['_FEEDITEMLIST']._serialized_end=184
  _globals['_GETFEEDREQUEST']._serialized_start=186
  _globals['_GETFEEDREQUEST']._serialized_end=250
  _globals['_FEEDRESPONSE']._serialized_start=252
  _globals['_FEEDRESPONSE']._serialized_end=335
  _globals['_GETFEEDRESPONSE']._serialized_start=337
  _globals['_GETFEEDRESPONSE']._serialized_end=428
  _globals['_FEEDSERVICE']._serialized_start=431
  _globals['_FEEDSERVICE']._serialized_end=609
# @@protoc_insertion_point(module_scope)
