# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.proto_files import feed_pb2 as app_dot_proto__files_dot_feed__pb2


class FeedServiceStub(object):
    """Feed Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFeed = channel.unary_unary(
                '/feed.FeedService/GetFeed',
                request_serializer=app_dot_proto__files_dot_feed__pb2.GetFeedRequest.SerializeToString,
                response_deserializer=app_dot_proto__files_dot_feed__pb2.GetFeedResponse.FromString,
                )
        self.AddToFeed = channel.unary_unary(
                '/feed.FeedService/AddToFeed',
                request_serializer=app_dot_proto__files_dot_feed__pb2.FeedItem.SerializeToString,
                response_deserializer=app_dot_proto__files_dot_feed__pb2.FeedResponse.FromString,
                )
        self.RemoveFromFeed = channel.unary_unary(
                '/feed.FeedService/RemoveFromFeed',
                request_serializer=app_dot_proto__files_dot_feed__pb2.FeedItem.SerializeToString,
                response_deserializer=app_dot_proto__files_dot_feed__pb2.FeedResponse.FromString,
                )


class FeedServiceServicer(object):
    """Feed Service Definition
    """

    def GetFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeed,
                    request_deserializer=app_dot_proto__files_dot_feed__pb2.GetFeedRequest.FromString,
                    response_serializer=app_dot_proto__files_dot_feed__pb2.GetFeedResponse.SerializeToString,
            ),
            'AddToFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToFeed,
                    request_deserializer=app_dot_proto__files_dot_feed__pb2.FeedItem.FromString,
                    response_serializer=app_dot_proto__files_dot_feed__pb2.FeedResponse.SerializeToString,
            ),
            'RemoveFromFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromFeed,
                    request_deserializer=app_dot_proto__files_dot_feed__pb2.FeedItem.FromString,
                    response_serializer=app_dot_proto__files_dot_feed__pb2.FeedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'feed.FeedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FeedService(object):
    """Feed Service Definition
    """

    @staticmethod
    def GetFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/feed.FeedService/GetFeed',
            app_dot_proto__files_dot_feed__pb2.GetFeedRequest.SerializeToString,
            app_dot_proto__files_dot_feed__pb2.GetFeedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/feed.FeedService/AddToFeed',
            app_dot_proto__files_dot_feed__pb2.FeedItem.SerializeToString,
            app_dot_proto__files_dot_feed__pb2.FeedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFromFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/feed.FeedService/RemoveFromFeed',
            app_dot_proto__files_dot_feed__pb2.FeedItem.SerializeToString,
            app_dot_proto__files_dot_feed__pb2.FeedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
