# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_files/auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto_files/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto_files/auth.proto\x12\x04\x61uth\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"5\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"\"\n\nOTPRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\"\x1e\n\x0bOTPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\":\n\x10VerifyOTPRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x10\n\x08otp_code\x18\x02 \x01(\t\"\"\n\x11VerifyOTPResponse\x12\r\n\x05token\x18\x01 \x01(\t\"/\n\x15\x46orgotPasswordRequest\x12\x16\n\x0e\x65mail_or_phone\x18\x01 \x01(\t\")\n\x16\x46orgotPasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"V\n\x14ResetPasswordRequest\x12\x16\n\x0e\x65mail_or_phone\x18\x01 \x01(\t\x12\x10\n\x08otp_code\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t\"(\n\x15ResetPasswordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc4\x02\n\x0b\x41uthService\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12.\n\x07SendOTP\x12\x10.auth.OTPRequest\x1a\x11.auth.OTPResponse\x12<\n\tVerifyOTP\x12\x16.auth.VerifyOTPRequest\x1a\x17.auth.VerifyOTPResponse\x12K\n\x0e\x46orgotPassword\x12\x1b.auth.ForgotPasswordRequest\x1a\x1c.auth.ForgotPasswordResponse\x12H\n\rResetPassword\x12\x1a.auth.ResetPasswordRequest\x1a\x1b.auth.ResetPasswordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=32
  _globals['_LOGINREQUEST']._serialized_end=79
  _globals['_LOGINRESPONSE']._serialized_start=81
  _globals['_LOGINRESPONSE']._serialized_end=134
  _globals['_OTPREQUEST']._serialized_start=136
  _globals['_OTPREQUEST']._serialized_end=170
  _globals['_OTPRESPONSE']._serialized_start=172
  _globals['_OTPRESPONSE']._serialized_end=202
  _globals['_VERIFYOTPREQUEST']._serialized_start=204
  _globals['_VERIFYOTPREQUEST']._serialized_end=262
  _globals['_VERIFYOTPRESPONSE']._serialized_start=264
  _globals['_VERIFYOTPRESPONSE']._serialized_end=298
  _globals['_FORGOTPASSWORDREQUEST']._serialized_start=300
  _globals['_FORGOTPASSWORDREQUEST']._serialized_end=347
  _globals['_FORGOTPASSWORDRESPONSE']._serialized_start=349
  _globals['_FORGOTPASSWORDRESPONSE']._serialized_end=390
  _globals['_RESETPASSWORDREQUEST']._serialized_start=392
  _globals['_RESETPASSWORDREQUEST']._serialized_end=478
  _globals['_RESETPASSWORDRESPONSE']._serialized_start=480
  _globals['_RESETPASSWORDRESPONSE']._serialized_end=520
  _globals['_AUTHSERVICE']._serialized_start=523
  _globals['_AUTHSERVICE']._serialized_end=847
# @@protoc_insertion_point(module_scope)
