# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto_files.posts import post_pb2 as post__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in post_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PostsServiceStub(object):
    """Posts Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/posts.PostsService/CreatePost',
                request_serializer=post__pb2.PostCreateRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.GetPost = channel.unary_unary(
                '/posts.PostsService/GetPost',
                request_serializer=post__pb2.PostRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.UpdatePost = channel.unary_unary(
                '/posts.PostsService/UpdatePost',
                request_serializer=post__pb2.PostUpdateRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.DeletePost = channel.unary_unary(
                '/posts.PostsService/DeletePost',
                request_serializer=post__pb2.PostRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.GetPostsByUser = channel.unary_unary(
                '/posts.PostsService/GetPostsByUser',
                request_serializer=post__pb2.GetPostsByUserRequest.SerializeToString,
                response_deserializer=post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.LikePost = channel.unary_unary(
                '/posts.PostsService/LikePost',
                request_serializer=post__pb2.LikePostRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.UnlikePost = channel.unary_unary(
                '/posts.PostsService/UnlikePost',
                request_serializer=post__pb2.LikePostRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)


class PostsServiceServicer(object):
    """Posts Service Definition
    """

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LikePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlikePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=post__pb2.PostCreateRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=post__pb2.PostRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'UpdatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePost,
                    request_deserializer=post__pb2.PostUpdateRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=post__pb2.PostRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'GetPostsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostsByUser,
                    request_deserializer=post__pb2.GetPostsByUserRequest.FromString,
                    response_serializer=post__pb2.PostListResponse.SerializeToString,
            ),
            'LikePost': grpc.unary_unary_rpc_method_handler(
                    servicer.LikePost,
                    request_deserializer=post__pb2.LikePostRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'UnlikePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlikePost,
                    request_deserializer=post__pb2.LikePostRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'posts.PostsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('posts.PostsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PostsService(object):
    """Posts Service Definition
    """

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/CreatePost',
            post__pb2.PostCreateRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetPost',
            post__pb2.PostRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/UpdatePost',
            post__pb2.PostUpdateRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/DeletePost',
            post__pb2.PostRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetPostsByUser',
            post__pb2.GetPostsByUserRequest.SerializeToString,
            post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LikePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/LikePost',
            post__pb2.LikePostRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlikePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/UnlikePost',
            post__pb2.LikePostRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
