# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import property_pb2 as property__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in property_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PropertyServiceStub(object):
    """Property Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProperty = channel.unary_unary(
                '/property.PropertyService/CreateProperty',
                request_serializer=property__pb2.Property.SerializeToString,
                response_deserializer=property__pb2.PropertyResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/property.PropertyService/GetProperty',
                request_serializer=property__pb2.PropertyRequest.SerializeToString,
                response_deserializer=property__pb2.PropertyResponse.FromString,
                _registered_method=True)
        self.UpdateProperty = channel.unary_unary(
                '/property.PropertyService/UpdateProperty',
                request_serializer=property__pb2.Property.SerializeToString,
                response_deserializer=property__pb2.PropertyResponse.FromString,
                _registered_method=True)
        self.DeleteProperty = channel.unary_unary(
                '/property.PropertyService/DeleteProperty',
                request_serializer=property__pb2.PropertyRequest.SerializeToString,
                response_deserializer=property__pb2.PropertyResponse.FromString,
                _registered_method=True)
        self.SearchProperties = channel.unary_unary(
                '/property.PropertyService/SearchProperties',
                request_serializer=property__pb2.PropertySearchRequest.SerializeToString,
                response_deserializer=property__pb2.PropertyListResponse.FromString,
                _registered_method=True)
        self.ListProperties = channel.unary_unary(
                '/property.PropertyService/ListProperties',
                request_serializer=property__pb2.PropertyRequest.SerializeToString,
                response_deserializer=property__pb2.PropertyListResponse.FromString,
                _registered_method=True)
        self.IncrementViewCount = channel.unary_unary(
                '/property.PropertyService/IncrementViewCount',
                request_serializer=property__pb2.PropertyRequest.SerializeToString,
                response_deserializer=property__pb2.PropertyResponse.FromString,
                _registered_method=True)


class PropertyServiceServicer(object):
    """Property Service Definition
    """

    def CreateProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementViewCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PropertyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProperty,
                    request_deserializer=property__pb2.Property.FromString,
                    response_serializer=property__pb2.PropertyResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=property__pb2.PropertyRequest.FromString,
                    response_serializer=property__pb2.PropertyResponse.SerializeToString,
            ),
            'UpdateProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProperty,
                    request_deserializer=property__pb2.Property.FromString,
                    response_serializer=property__pb2.PropertyResponse.SerializeToString,
            ),
            'DeleteProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProperty,
                    request_deserializer=property__pb2.PropertyRequest.FromString,
                    response_serializer=property__pb2.PropertyResponse.SerializeToString,
            ),
            'SearchProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProperties,
                    request_deserializer=property__pb2.PropertySearchRequest.FromString,
                    response_serializer=property__pb2.PropertyListResponse.SerializeToString,
            ),
            'ListProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProperties,
                    request_deserializer=property__pb2.PropertyRequest.FromString,
                    response_serializer=property__pb2.PropertyListResponse.SerializeToString,
            ),
            'IncrementViewCount': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementViewCount,
                    request_deserializer=property__pb2.PropertyRequest.FromString,
                    response_serializer=property__pb2.PropertyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'property.PropertyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('property.PropertyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PropertyService(object):
    """Property Service Definition
    """

    @staticmethod
    def CreateProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/property.PropertyService/CreateProperty',
            property__pb2.Property.SerializeToString,
            property__pb2.PropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/property.PropertyService/GetProperty',
            property__pb2.PropertyRequest.SerializeToString,
            property__pb2.PropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/property.PropertyService/UpdateProperty',
            property__pb2.Property.SerializeToString,
            property__pb2.PropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/property.PropertyService/DeleteProperty',
            property__pb2.PropertyRequest.SerializeToString,
            property__pb2.PropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/property.PropertyService/SearchProperties',
            property__pb2.PropertySearchRequest.SerializeToString,
            property__pb2.PropertyListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/property.PropertyService/ListProperties',
            property__pb2.PropertyRequest.SerializeToString,
            property__pb2.PropertyListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementViewCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/property.PropertyService/IncrementViewCount',
            property__pb2.PropertyRequest.SerializeToString,
            property__pb2.PropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
